src/WaybackWeather/Models/EnvironmentVariables.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WaybackWeather.Models
{
    public class EnvironmentVariables
    {
        public static string DarkSkyKey = "b4f4b90e28e9bdf3271bead0f9804aad";
        public static string MapBoxToken = "pk.eyJ1IjoibGV2aWJpYm8iLCJhIjoiY2l6b2lvYmVuMDM3YjJxbzd2Yzlvbjl2MiJ9.SQO9hF6HuP-NasJH9KPLnA";

    }
}

src/WaybackWeather/Models/InputRequest.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RestSharp;
using RestSharp.Authenticators;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace WaybackWeather.Models
{
    public class InputRequest
    {
        public string Location { get; set; }
        public float Lat { get; set; }
        public float Long { get; set; }
        public long Date { get; set; }
        public string LocationResult { get; set; }

        public void GetLatLong()
        {
            RestClient client = new RestClient("https://api.mapbox.com");
            Location = Location.Replace(" ", "+");    //url seems to prefer + instead of space
            RestRequest request = new RestRequest("/geocoding/v5/mapbox.places/" + Location + ".json?access_token="+ EnvironmentVariables.MapBoxToken, Method.GET);
            RestResponse response = new RestResponse();
            Task.Run(async () =>
            {
                response = await GetResponseContentAsync(client, request) as RestResponse;
            }).Wait();

            JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(response.Content);
            object[] features = JsonConvert.DeserializeObject<object[]>(jsonResponse["features"].ToString());
            JObject firstElement = JsonConvert.DeserializeObject<JObject>(features[0].ToString());
            string[] center = JsonConvert.DeserializeObject<string[]>(firstElement["center"].ToString());

            Long = float.Parse(center[0]);
            Lat = float.Parse(center[1]);
            LocationResult = firstElement["place_name"].ToString();
        }

        public Dictionary<string, string> GetWeather()
        {
            RestClient client = new RestClient("https://api.darksky.net");
            RestRequest request = new RestRequest($"/forecast/{EnvironmentVariables.DarkSkyKey}/{Lat},{Long},{Date}", Method.GET);
            RestResponse response = new RestResponse();

            Task.Run(async () =>
            {
                response = await GetResponseContentAsync(client, request) as RestResponse;
            }).Wait();

            try
            {
                JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(response.Content);
                JObject daily = JsonConvert.DeserializeObject<JObject>(jsonResponse["daily"].ToString());
                JObject[] data = JsonConvert.DeserializeObject<JObject[]>(daily["data"].ToString());
                JObject firstElement = JsonConvert.DeserializeObject<JObject>(data[0].ToString());
                return new Dictionary<string, string>
                {
                    ["summary"] = firstElement["summary"].ToString(),
                    ["temperatureMin"] = firstElement["temperatureMin"].ToString(),
                    ["temperatureMax"] = firstElement["temperatureMax"].ToString(),
                    ["foundLocation"] = LocationResult
                };
            }
            catch
            {
                return new Dictionary<string, string>()
                {
                    //Force summary to null in order to check validation on front end
                    ["summary"] = null
                };
            }
        }

        public static Task<IRestResponse> GetResponseContentAsync(RestClient theClient, RestRequest theRequest)
        {
            var tcs = new TaskCompletionSource<IRestResponse>();
            theClient.ExecuteAsync(theRequest, response => {
                tcs.SetResult(response);
            });
            return tcs.Task;
        }
    }
}

src/WaybackWeather/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WaybackWeather.Models;

namespace WaybackWeather.Controllers
{
    public class HomeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult NewRequest()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NewRequest(InputRequest input, string dateString)
        {
            long date = new DateTimeOffset(DateTime.Parse(dateString)).ToUnixTimeSeconds();
            input.Date = date;
            return RedirectToAction("Index");
        }
    }
}

src/WaybackWeather/Controllers/InputRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WaybackWeather.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace WaybackWeather.Controllers
{
    public class InputRequestController : Controller
    {
        // GET: /<controller>/
        public IActionResult NewRequest()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RequestPartial(InputRequest input, string dateString)
        {
            long date = new DateTimeOffset(DateTime.Parse(dateString)).ToUnixTimeSeconds();
            input.Date = date;
            try
            {
                input.GetLatLong();
            }
            catch
            {
                return View("InvalidLocation");
            }
            ViewBag.Weather = input.GetWeather();
            if (ViewBag.Weather["summary"] == null)
            {
                return View("InvalidDate");
            }

            return View();
        }


    }
}

src/WaybackWeather/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Wayback Weather";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Wayback Weather</h1>
<hr />
@Html.ActionLink("New Request", "NewRequest", "InputRequest")

src/WaybackWeather/Views/InputRequest/InvalidDate.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>We couldn't find data for that date.</p>

src/WaybackWeather/Views/InputRequest/InvalidLocation.cshtml
<p>Invalid location.</p>

src/WaybackWeather/Views/InputRequest/NewRequest.cshtml
@{
    ViewData["Title"] = "Find Historical Data";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model WaybackWeather.Models.InputRequest

<script>
    $(function () {
        $("form").submit(function (event) {
            event.preventDefault();
            $("#response").addClass("well");
            $("#response").html("<p>Using Wayback Weather Machine...</p>");
            $.ajax({
                type: "POST",
                url: '@Url.Action("RequestPartial", "InputRequest")',
                data: $(this).serialize(),
                datatype: 'json',
                success: function (response) {
                    $("#response").html(response);
                }
            })
        })
    })
</script>

<h1>Find Historical Data</h1>
<hr />
<form asp-controller="InputRequest" asp-action="NewRequest" class="row">
    <div class="form-group col-xs-12 col-md-6">
        <label asp-for="Location"></label>
        <input asp-for="Location" type="text" class="form-control" required/>
    </div>
    <div class="form-group col-xs-12 col-md-6">
        <label>Date</label>
        <input type="date" name="dateString" class="form-control" required/>
    </div>
    <div class="col-xs-12">
        <button type="submit" class="btn">Submit</button>
    </div>
</form>

<div id="response"></div>

src/WaybackWeather/Views/InputRequest/RequestPartial.cshtml
<p>Data for @ViewBag.Weather["foundLocation"]:</p>
<p>@ViewBag.Weather["summary"]</p>
<p>The high was @ViewBag.Weather["temperatureMax"]°F and the low was @ViewBag.Weather["temperatureMin"]°F.</p>
       

src/WaybackWeather/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <script src="~/js/jquery-3.1.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <main class="container">
        @RenderBody()
    </main>
    <footer><a href="https://darksky.net/poweredby/">Powered by Dark Sky</a></footer>
</body>
</html>